import React from 'react';
import { Row, Col, Form, Button, Card, Table, Badge } from 'react-bootstrap';

const Reports = () => (
  <div>
    <div className="d-flex justify-content-between align-items-center mb-4">
      <h2>Reports & Analytics</h2>
      <Button variant="primary">Generate Report</Button>
    </div>

    {/* Report Filters */}
    <Card className="mb-4">
      <Card.Body>
        <Row>
          <Col md={3}>
            <Form.Select>
              <option>Select Report Type</option>
              <option>User Activity</option>
              <option>Prescription Analytics</option>
              <option>Medicine Usage</option>
              <option>Compliance Report</option>
            </Form.Select>
          </Col>
          <Col md={2}>
            <Form.Control type="date" />
          </Col>
          <Col md={2}>
            <Form.Control type="date" />
          </Col>
          <Col md={2}>
            <Form.Select>
              <option>All Users</option>
              <option>Patients Only</option>
              <option>Doctors Only</option>
            </Form.Select>
          </Col>
          <Col md={2}>
            <Button variant="primary" className="w-100">Generate</Button>
          </Col>
          <Col md={1}>
            <Button variant="outline-secondary" className="w-100">Export</Button>
          </Col>
        </Row>
      </Card.Body>
    </Card>

    {/* Quick Stats */}
    <Row className="mb-4">
      <Col md={3}>
        <Card className="text-center">
          <Card.Body>
            <h3 className="text-primary">1,234</h3>
            <p className="text-muted mb-0">Total Reports</p>
            <small className="text-success">+15% this month</small>
          </Card.Body>
        </Card>
      </Col>
      <Col md={3}>
        <Card className="text-center">
          <Card.Body>
            <h3 className="text-success">89%</h3>
            <p className="text-muted mb-0">Compliance Rate</p>
            <small className="text-success">+3% this month</small>
          </Card.Body>
        </Card>
      </Col>
      <Col md={3}>
        <Card className="text-center">
          <Card.Body>
            <h3 className="text-warning">456</h3>
            <p className="text-muted mb-0">Active Prescriptions</p>
            <small className="text-success">+8% this month</small>
          </Card.Body>
        </Card>
      </Col>
      <Col md={3}>
        <Card className="text-center">
          <Card.Body>
            <h3 className="text-info">78</h3>
            <p className="text-muted mb-0">Doctors Active</p>
            <small className="text-success">+2% this month</small>
          </Card.Body>
        </Card>
      </Col>
    </Row>

    {/* Recent Reports */}
    <Card>
      <Card.Header>
        <div className="d-flex justify-content-between align-items-center">
          <h5 className="mb-0">Recent Reports</h5>
          <Button variant="outline-secondary" size="sm">View All</Button>
        </div>
      </Card.Header>
      <Card.Body>
        <Table responsive hover>
          <thead>
            <tr>
              <th>Report Name</th>
              <th>Type</th>
              <th>Generated By</th>
              <th>Date</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Monthly User Activity Report</td>
              <td><Badge bg="primary">User Activity</Badge></td>
              <td>Admin User</td>
              <td>Mar 15, 2024</td>
              <td><Badge bg="success">Completed</Badge></td>
              <td>
                <Button variant="outline-primary" size="sm" className="me-1">View</Button>
                <Button variant="outline-secondary" size="sm">Download</Button>
              </td>
            </tr>
            <tr>
              <td>Prescription Analytics Q1 2024</td>
              <td><Badge bg="warning">Prescription Analytics</Badge></td>
              <td>Dr. Smith</td>
              <td>Mar 10, 2024</td>
              <td><Badge bg="success">Completed</Badge></td>
              <td>
                <Button variant="outline-primary" size="sm" className="me-1">View</Button>
                <Button variant="outline-secondary" size="sm">Download</Button>
              </td>
            </tr>
            <tr>
              <td>Medicine Usage Report</td>
              <td><Badge bg="info">Medicine Usage</Badge></td>
              <td>Pharmacy Manager</td>
              <td>Mar 8, 2024</td>
              <td><Badge bg="secondary">Processing</Badge></td>
              <td>
                <Button variant="outline-secondary" size="sm" disabled>Processing...</Button>
              </td>
            </tr>
          </tbody>
        </Table>
      </Card.Body>
    </Card>
  </div>
);

export default Reports;
